services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - '11434:11434'
  #   volumes:
  #     - ollama_models:/root/.ollama
  #   restart: unless-stopped
  #   entrypoint:
  #     [
  #       '/bin/sh',
  #       '-c',
  #       'ollama serve & sleep 3 && ollama pull openchat && tail -f /dev/null',
  #     ]
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  llama:
    build: images/llama/Dockerfile
    container_name: llama
    ports:
      - '8000:8000'
    volumes:
      - ./models:/models
    command: ./server -m /models/mistral-7b-instruct-v0.1.Q4_K_M.gguf -c 4096
  oraculo:
    build:
      context: .
      dockerfile: images/node/Dockerfile
    container_name: oraculo
    ports:
      - '8080:8080'
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./public:/app/public
      - ./.env:/app/.env
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models:
